twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals: 
        cle_public: '%cle_public%'
    form_themes: ['bootstrap_4_layout.html.twig']
